//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imfree.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class IMFREEEntities : DbContext
    {
        public IMFREEEntities()
            : base("name=IMFREEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcceptedUser> AcceptedUser { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Contacts> Contacts { get; set; }
        public DbSet<CustomReport> CustomReport { get; set; }
        public DbSet<ErrorLog> ErrorLog { get; set; }
        public DbSet<Item> Item { get; set; }
        public DbSet<PrivateUser> PrivateUser { get; set; }
        public DbSet<Suggest> Suggest { get; set; }
        public DbSet<Users> Users { get; set; }
    
        public virtual int CategoryCreate(string categoryname, string iconfilename)
        {
            var categorynameParameter = categoryname != null ?
                new ObjectParameter("categoryname", categoryname) :
                new ObjectParameter("categoryname", typeof(string));
    
            var iconfilenameParameter = iconfilename != null ?
                new ObjectParameter("iconfilename", iconfilename) :
                new ObjectParameter("iconfilename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CategoryCreate", categorynameParameter, iconfilenameParameter);
        }
    
        public virtual int CategoryDataInit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CategoryDataInit");
        }
    
        public virtual int CategoryDelete()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CategoryDelete");
        }
    
        public virtual int CategoryGetInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CategoryGetInfo");
        }
    
        public virtual ObjectResult<CategoryGetList_Result> CategoryGetList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CategoryGetList_Result>("CategoryGetList");
        }
    
        public virtual int CategoryUpdate(Nullable<byte> categorysn, string categoryname, string iconfilename)
        {
            var categorysnParameter = categorysn.HasValue ?
                new ObjectParameter("categorysn", categorysn) :
                new ObjectParameter("categorysn", typeof(byte));
    
            var categorynameParameter = categoryname != null ?
                new ObjectParameter("categoryname", categoryname) :
                new ObjectParameter("categoryname", typeof(string));
    
            var iconfilenameParameter = iconfilename != null ?
                new ObjectParameter("iconfilename", iconfilename) :
                new ObjectParameter("iconfilename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CategoryUpdate", categorysnParameter, categorynameParameter, iconfilenameParameter);
        }
    
        public virtual ObjectResult<CategoryWithItemGetList_Result> CategoryWithItemGetList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CategoryWithItemGetList_Result>("CategoryWithItemGetList");
        }
    
        public virtual int ContactsCreate(Nullable<long> usersn, string hashphone)
        {
            var usersnParameter = usersn.HasValue ?
                new ObjectParameter("usersn", usersn) :
                new ObjectParameter("usersn", typeof(long));
    
            var hashphoneParameter = hashphone != null ?
                new ObjectParameter("hashphone", hashphone) :
                new ObjectParameter("hashphone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ContactsCreate", usersnParameter, hashphoneParameter);
        }
    
        public virtual int ContactsDelete(Nullable<long> usersn, string hashphone)
        {
            var usersnParameter = usersn.HasValue ?
                new ObjectParameter("usersn", usersn) :
                new ObjectParameter("usersn", typeof(long));
    
            var hashphoneParameter = hashphone != null ?
                new ObjectParameter("hashphone", hashphone) :
                new ObjectParameter("hashphone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ContactsDelete", usersnParameter, hashphoneParameter);
        }
    
        public virtual ObjectResult<string> ContactsInstallUserList(Nullable<long> usersn, ObjectParameter totalCount)
        {
            var usersnParameter = usersn.HasValue ?
                new ObjectParameter("usersn", usersn) :
                new ObjectParameter("usersn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ContactsInstallUserList", usersnParameter, totalCount);
        }
    
        public virtual int CustomReportCreate(string report)
        {
            var reportParameter = report != null ?
                new ObjectParameter("Report", report) :
                new ObjectParameter("Report", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CustomReportCreate", reportParameter);
        }
    
        public virtual ObjectResult<CustomReportGetList_Result> CustomReportGetList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomReportGetList_Result>("CustomReportGetList");
        }
    
        public virtual int ErrorLogCreate(string ip, string uri, string source, string method, string error, string trace, string json)
        {
            var ipParameter = ip != null ?
                new ObjectParameter("ip", ip) :
                new ObjectParameter("ip", typeof(string));
    
            var uriParameter = uri != null ?
                new ObjectParameter("uri", uri) :
                new ObjectParameter("uri", typeof(string));
    
            var sourceParameter = source != null ?
                new ObjectParameter("source", source) :
                new ObjectParameter("source", typeof(string));
    
            var methodParameter = method != null ?
                new ObjectParameter("method", method) :
                new ObjectParameter("method", typeof(string));
    
            var errorParameter = error != null ?
                new ObjectParameter("error", error) :
                new ObjectParameter("error", typeof(string));
    
            var traceParameter = trace != null ?
                new ObjectParameter("trace", trace) :
                new ObjectParameter("trace", typeof(string));
    
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ErrorLogCreate", ipParameter, uriParameter, sourceParameter, methodParameter, errorParameter, traceParameter, jsonParameter);
        }
    
        public virtual ObjectResult<ErrorLogGetList_Result> ErrorLogGetList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ErrorLogGetList_Result>("ErrorLogGetList");
        }
    
        public virtual int ItemCreate(Nullable<byte> categorysn, string itemname, string cardfilename)
        {
            var categorysnParameter = categorysn.HasValue ?
                new ObjectParameter("categorysn", categorysn) :
                new ObjectParameter("categorysn", typeof(byte));
    
            var itemnameParameter = itemname != null ?
                new ObjectParameter("itemname", itemname) :
                new ObjectParameter("itemname", typeof(string));
    
            var cardfilenameParameter = cardfilename != null ?
                new ObjectParameter("cardfilename", cardfilename) :
                new ObjectParameter("cardfilename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ItemCreate", categorysnParameter, itemnameParameter, cardfilenameParameter);
        }
    
        public virtual ObjectResult<ItemGetList_Result> ItemGetList(Nullable<byte> categorysn)
        {
            var categorysnParameter = categorysn.HasValue ?
                new ObjectParameter("categorysn", categorysn) :
                new ObjectParameter("categorysn", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ItemGetList_Result>("ItemGetList", categorysnParameter);
        }
    
        public virtual int PrivateUserCreate(Nullable<long> suggestsn, string hashphone)
        {
            var suggestsnParameter = suggestsn.HasValue ?
                new ObjectParameter("suggestsn", suggestsn) :
                new ObjectParameter("suggestsn", typeof(long));
    
            var hashphoneParameter = hashphone != null ?
                new ObjectParameter("hashphone", hashphone) :
                new ObjectParameter("hashphone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PrivateUserCreate", suggestsnParameter, hashphoneParameter);
        }
    
        public virtual int SuggestCreate(ObjectParameter suggestsn, Nullable<long> usersn, string hashphone, Nullable<byte> categorysn, Nullable<byte> itemsn)
        {
            var usersnParameter = usersn.HasValue ?
                new ObjectParameter("usersn", usersn) :
                new ObjectParameter("usersn", typeof(long));
    
            var hashphoneParameter = hashphone != null ?
                new ObjectParameter("hashphone", hashphone) :
                new ObjectParameter("hashphone", typeof(string));
    
            var categorysnParameter = categorysn.HasValue ?
                new ObjectParameter("categorysn", categorysn) :
                new ObjectParameter("categorysn", typeof(byte));
    
            var itemsnParameter = itemsn.HasValue ?
                new ObjectParameter("itemsn", itemsn) :
                new ObjectParameter("itemsn", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuggestCreate", suggestsn, usersnParameter, hashphoneParameter, categorysnParameter, itemsnParameter);
        }
    
        public virtual int SuggestDelete(Nullable<long> usersn, Nullable<long> suggestsn)
        {
            var usersnParameter = usersn.HasValue ?
                new ObjectParameter("usersn", usersn) :
                new ObjectParameter("usersn", typeof(long));
    
            var suggestsnParameter = suggestsn.HasValue ?
                new ObjectParameter("suggestsn", suggestsn) :
                new ObjectParameter("suggestsn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuggestDelete", usersnParameter, suggestsnParameter);
        }
    
        public virtual ObjectResult<SuggestFriendList_Result> SuggestFriendList(Nullable<long> usersn)
        {
            var usersnParameter = usersn.HasValue ?
                new ObjectParameter("usersn", usersn) :
                new ObjectParameter("usersn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SuggestFriendList_Result>("SuggestFriendList", usersnParameter);
        }
    
        public virtual ObjectResult<SuggestMyList_Result> SuggestMyList(Nullable<long> usersn)
        {
            var usersnParameter = usersn.HasValue ?
                new ObjectParameter("usersn", usersn) :
                new ObjectParameter("usersn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SuggestMyList_Result>("SuggestMyList", usersnParameter);
        }
    
        public virtual int UserCreate(ObjectParameter usersn, string accesstoken, string guid, string hashphone, string deviceid, string pushkey)
        {
            var accesstokenParameter = accesstoken != null ?
                new ObjectParameter("accesstoken", accesstoken) :
                new ObjectParameter("accesstoken", typeof(string));
    
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            var hashphoneParameter = hashphone != null ?
                new ObjectParameter("hashphone", hashphone) :
                new ObjectParameter("hashphone", typeof(string));
    
            var deviceidParameter = deviceid != null ?
                new ObjectParameter("deviceid", deviceid) :
                new ObjectParameter("deviceid", typeof(string));
    
            var pushkeyParameter = pushkey != null ?
                new ObjectParameter("pushkey", pushkey) :
                new ObjectParameter("pushkey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserCreate", usersn, accesstokenParameter, guidParameter, hashphoneParameter, deviceidParameter, pushkeyParameter);
        }
    
        public virtual int UserGetInfoByToken(string accesstoken, ObjectParameter usersn, ObjectParameter guid, ObjectParameter hashphone, ObjectParameter deviceid, ObjectParameter pushkey, ObjectParameter createdate, ObjectParameter updatedate)
        {
            var accesstokenParameter = accesstoken != null ?
                new ObjectParameter("accesstoken", accesstoken) :
                new ObjectParameter("accesstoken", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserGetInfoByToken", accesstokenParameter, usersn, guid, hashphone, deviceid, pushkey, createdate, updatedate);
        }
    
        public virtual int UserGetInfoByusersn(Nullable<long> usersn, ObjectParameter accesstoken, ObjectParameter guid, ObjectParameter hashphone, ObjectParameter deviceid, ObjectParameter pushkey, ObjectParameter createdate, ObjectParameter updatedate)
        {
            var usersnParameter = usersn.HasValue ?
                new ObjectParameter("usersn", usersn) :
                new ObjectParameter("usersn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserGetInfoByusersn", usersnParameter, accesstoken, guid, hashphone, deviceid, pushkey, createdate, updatedate);
        }
    
        public virtual int UserUpdate(string accesstoken, string guid, string hashphone, string deviceid, string pushkey)
        {
            var accesstokenParameter = accesstoken != null ?
                new ObjectParameter("accesstoken", accesstoken) :
                new ObjectParameter("accesstoken", typeof(string));
    
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            var hashphoneParameter = hashphone != null ?
                new ObjectParameter("hashphone", hashphone) :
                new ObjectParameter("hashphone", typeof(string));
    
            var deviceidParameter = deviceid != null ?
                new ObjectParameter("deviceid", deviceid) :
                new ObjectParameter("deviceid", typeof(string));
    
            var pushkeyParameter = pushkey != null ?
                new ObjectParameter("pushkey", pushkey) :
                new ObjectParameter("pushkey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserUpdate", accesstokenParameter, guidParameter, hashphoneParameter, deviceidParameter, pushkeyParameter);
        }
    }
}
